name: Build APK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Устанавливаем Node 10 (только он работает с Realm 2.x)
      - name: Setup Node.js 10
        uses: actions/setup-node@v4
        with:
          node-version: 10

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --network-timeout 1000000

      # Устанавливаем JDK и Android SDK
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Сборка APK
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      # Артефакт APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tronwallet-apk
          path: android/app/build/outputs/apk/release/app-release.apk