name: Build Tron Wallet

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 12
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install Yarn
        run: npm install -g yarn

      # FIX REALM — заменяем его пустым модулем, чтобы Yarn не собирал нативные бинари
      - name: Disable Realm native module
        run: |
          mkdir -p ./patches
          echo '{}' > ./patches/realm+2.12.0.patch
          yarn add patch-package
          yarn patch-package realm

      - name: Install dependencies
        run: yarn install --network-timeout 1000000

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tronwallet-apk
          path: android/app/build/outputs/apk/release/*.apk